
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1000, 'AF','AFGHANISTAN','Afghanistan','AFG','004')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1001, 'AL','ALBANIA','Albania','ALB','008')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1002, 'DZ','ALGERIA','Algeria','DZA','012')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1003, 'AS','AMERICAN SAMOA','American Samoa','ASM','016')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1004, 'AD','ANDORRA','Andorra','AND','020')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1005, 'AO','ANGOLA','Angola','AGO','024')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1006, 'AI','ANGUILLA','Anguilla','AIA','660')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1007, 'AQ','ANTARCTICA','Antarctica',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1008, 'AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','028')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1009, 'AR','ARGENTINA','Argentina','ARG','032')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1010, 'AM','ARMENIA','Armenia','ARM','051')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1011, 'AW','ARUBA','Aruba','ABW','533')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1012, 'AU','AUSTRALIA','Australia','AUS','036')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1013, 'AT','AUSTRIA','Austria','AUT','040')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1014, 'AZ','AZERBAIJAN','Azerbaijan','AZE','031')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1015, 'BS','BAHAMAS','Bahamas','BHS','044')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1016, 'BH','BAHRAIN','Bahrain','BHR','048')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1017, 'BD','BANGLADESH','Bangladesh','BGD','050')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1018, 'BB','BARBADOS','Barbados','BRB','052')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1019, 'BY','BELARUS','Belarus','BLR','112')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1020, 'BE','BELGIUM','Belgium','BEL','056')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1021, 'BZ','BELIZE','Belize','BLZ','084')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1022, 'BJ','BENIN','Benin','BEN','204')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1023, 'BM','BERMUDA','Bermuda','BMU','060')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1024, 'BT','BHUTAN','Bhutan','BTN','064')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1025, 'BO','BOLIVIA','Bolivia','BOL','068')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1026, 'BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','070')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1027, 'BW','BOTSWANA','Botswana','BWA','072')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1028, 'BV','BOUVET ISLAND','Bouvet Island',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1029, 'BR','BRAZIL','Brazil','BRA','076')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1030, 'IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1031, 'BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','096')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1032, 'BG','BULGARIA','Bulgaria','BGR','100')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1033, 'BF','BURKINA FASO','Burkina Faso','BFA','854')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1034, 'BI','BURUNDI','Burundi','BDI','108')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1035, 'KH','CAMBODIA','Cambodia','KHM','116')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1036, 'CM','CAMEROON','Cameroon','CMR','120')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1037, 'CA','CANADA','Canada','CAN','124')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1038, 'CV','CAPE VERDE','Cape Verde','CPV','132')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1039, 'KY','CAYMAN ISLANDS','Cayman Islands','CYM','136')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1040, 'CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1041, 'TD','CHAD','Chad','TCD','148')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1042, 'CL','CHILE','Chile','CHL','152')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1043, 'CN','CHINA','China','CHN','156')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1044, 'CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1045, 'CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1046, 'CO','COLOMBIA','Colombia','COL','170')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1047, 'KM','COMOROS','Comoros','COM','174')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1048, 'CG','CONGO','Congo','COG','178')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1049, 'CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1050, 'CK','COOK ISLANDS','Cook Islands','COK','184')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1051, 'CR','COSTA RICA','Costa Rica','CRI','188')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1052, 'CI','COTE D IVOIRE','Cote d Ivoire','CIV','384')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1053, 'HR','CROATIA','Croatia','HRV','191')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1054, 'CU','CUBA','Cuba','CUB','192')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1055, 'CY','CYPRUS','Cyprus','CYP','196')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1056, 'CZ','CZECH REPUBLIC','Czech Republic','CZE','203')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1057, 'DK','DENMARK','Denmark','DNK','208')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1058, 'DJ','DJIBOUTI','Djibouti','DJI','262')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1059, 'DM','DOMINICA','Dominica','DMA','212')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1060, 'DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1061, 'EC','ECUADOR','Ecuador','ECU','218')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1062, 'EG','EGYPT','Egypt','EGY','818')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1063, 'SV','EL SALVADOR','El Salvador','SLV','222')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1064, 'GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1065, 'ER','ERITREA','Eritrea','ERI','232')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1066, 'EE','ESTONIA','Estonia','EST','233')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1067, 'ET','ETHIOPIA','Ethiopia','ETH','231')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1068, 'FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK','238')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1069, 'FO','FAROE ISLANDS','Faroe Islands','FRO','234')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1070, 'FJ','FIJI','Fiji','FJI','242')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1071, 'FI','FINLAND','Finland','FIN','246')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1072, 'FR','FRANCE','France','FRA','250')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1073, 'GF','FRENCH GUIANA','French Guiana','GUF','254')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1074, 'PF','FRENCH POLYNESIA','French Polynesia','PYF','258')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1075, 'TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1076, 'GA','GABON','Gabon','GAB','266')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1077, 'GM','GAMBIA','Gambia','GMB','270')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1078, 'GE','GEORGIA','Georgia','GEO','268')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1079, 'DE','GERMANY','Germany','DEU','276')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1080, 'GH','GHANA','Ghana','GHA','288')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1081, 'GI','GIBRALTAR','Gibraltar','GIB','292')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1082, 'GR','GREECE','Greece','GRC','300')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1083, 'GL','GREENLAND','Greenland','GRL','304')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1084, 'GD','GRENADA','Grenada','GRD','308')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1085, 'GP','GUADELOUPE','Guadeloupe','GLP','312')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1086, 'GU','GUAM','Guam','GUM','316')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1087, 'GT','GUATEMALA','Guatemala','GTM','320')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1088, 'GN','GUINEA','Guinea','GIN','324')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1089, 'GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1090, 'GY','GUYANA','Guyana','GUY','328')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1091, 'HT','HAITI','Haiti','HTI','332')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1092, 'HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1093, 'VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT','336')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1094, 'HN','HONDURAS','Honduras','HND','340')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1095, 'HK','HONG KONG','Hong Kong','HKG','344')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1096, 'HU','HUNGARY','Hungary','HUN','348')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1097, 'IS','ICELAND','Iceland','ISL','352')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1098, 'IN','INDIA','India','IND','356')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1099, 'ID','INDONESIA','Indonesia','IDN','360')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1100, 'IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1101, 'IQ','IRAQ','Iraq','IRQ','368')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1102, 'IE','IRELAND','Ireland','IRL','372')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1103, 'IL','ISRAEL','Israel','ISR','376')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1104, 'IT','ITALY','Italy','ITA','380')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1105, 'JM','JAMAICA','Jamaica','JAM','388')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1106, 'JP','JAPAN','Japan','JPN','392')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1107, 'JO','JORDAN','Jordan','JOR','400')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1108, 'KZ','KAZAKHSTAN','Kazakhstan','KAZ','398')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1109, 'KE','KENYA','Kenya','KEN','404')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1110, 'KI','KIRIBATI','Kiribati','KIR','296')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1111, 'KP','KOREA, DEMOCRATIC PEOPLE S REPUBLIC OF','Korea, Democratic People s Republic of','PRK','408')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1112, 'KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1113, 'KW','KUWAIT','Kuwait','KWT','414')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1114, 'KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1115, 'LA','LAO PEOPLE S DEMOCRATIC REPUBLIC','Lao People s Democratic Republic','LAO','418')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1116, 'LV','LATVIA','Latvia','LVA','428')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1117, 'LB','LEBANON','Lebanon','LBN','422')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1118, 'LS','LESOTHO','Lesotho','LSO','426')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1119, 'LR','LIBERIA','Liberia','LBR','430')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1120, 'LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1121, 'LI','LIECHTENSTEIN','Liechtenstein','LIE','438')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1122, 'LT','LITHUANIA','Lithuania','LTU','440')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1123, 'LU','LUXEMBOURG','Luxembourg','LUX','442')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1124, 'MO','MACAO','Macao','MAC','446')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1125, 'MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1126, 'MG','MADAGASCAR','Madagascar','MDG','450')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1127, 'MW','MALAWI','Malawi','MWI','454')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1128, 'MY','MALAYSIA','Malaysia','MYS','458')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1129, 'MV','MALDIVES','Maldives','MDV','462')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1130, 'ML','MALI','Mali','MLI','466')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1131, 'MT','MALTA','Malta','MLT','470')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1132, 'MH','MARSHALL ISLANDS','Marshall Islands','MHL','584')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1133, 'MQ','MARTINIQUE','Martinique','MTQ','474')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1134, 'MR','MAURITANIA','Mauritania','MRT','478')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1135, 'MU','MAURITIUS','Mauritius','MUS','480')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1136, 'YT','MAYOTTE','Mayotte',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1137, 'MX','MEXICO','Mexico','MEX','484')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1138, 'FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1139, 'MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1140, 'MC','MONACO','Monaco','MCO','492')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1141, 'MN','MONGOLIA','Mongolia','MNG','496')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1142, 'MS','MONTSERRAT','Montserrat','MSR','500')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1143, 'MA','MOROCCO','Morocco','MAR','504')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1144, 'MZ','MOZAMBIQUE','Mozambique','MOZ','508')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1145, 'MM','MYANMAR','Myanmar','MMR','104')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1146, 'NA','NAMIBIA','Namibia','NAM','516')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1147, 'NR','NAURU','Nauru','NRU','520')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1148, 'NP','NEPAL','Nepal','NPL','524')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1149, 'NL','NETHERLANDS','Netherlands','NLD','528')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1150, 'AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT','530')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1151, 'NC','NEW CALEDONIA','New Caledonia','NCL','540')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1152, 'NZ','NEW ZEALAND','New Zealand','NZL','554')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1153, 'NI','NICARAGUA','Nicaragua','NIC','558')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1154, 'NE','NIGER','Niger','NER','562')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1155, 'NG','NIGERIA','Nigeria','NGA','566')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1156, 'NU','NIUE','Niue','NIU','570')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1157, 'NF','NORFOLK ISLAND','Norfolk Island','NFK','574')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1158, 'MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1159, 'NO','NORWAY','Norway','NOR','578')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1160, 'OM','OMAN','Oman','OMN','512')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1161, 'PK','PAKISTAN','Pakistan','PAK','586')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1162, 'PW','PALAU','Palau','PLW','585')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1163, 'PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1164, 'PA','PANAMA','Panama','PAN','591')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1165, 'PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1166, 'PY','PARAGUAY','Paraguay','PRY','600')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1167, 'PE','PERU','Peru','PER','604')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1168, 'PH','PHILIPPINES','Philippines','PHL','608')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1169, 'PN','PITCAIRN','Pitcairn','PCN','612')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1170, 'PL','POLAND','Poland','POL','616')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1171, 'PT','PORTUGAL','Portugal','PRT','620')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1172, 'PR','PUERTO RICO','Puerto Rico','PRI','630')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1173, 'QA','QATAR','Qatar','QAT','634')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1174, 'RE','REUNION','Reunion','REU','638')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1175, 'RO','ROMANIA','Romania','ROM','642')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1176, 'RU','RUSSIAN FEDERATION','Russian Federation','RUS','643')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1177, 'RW','RWANDA','Rwanda','RWA','646')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1178, 'SH','SAINT HELENA','Saint Helena','SHN','654')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1179, 'KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1180, 'LC','SAINT LUCIA','Saint Lucia','LCA','662')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1181, 'PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM','666')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1182, 'VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1183, 'WS','SAMOA','Samoa','WSM','882')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1184, 'SM','SAN MARINO','San Marino','SMR','674')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1185, 'ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1186, 'SA','SAUDI ARABIA','Saudi Arabia','SAU','682')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1187, 'SN','SENEGAL','Senegal','SEN','686')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1188, 'CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1189, 'SC','SEYCHELLES','Seychelles','SYC','690')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1190, 'SL','SIERRA LEONE','Sierra Leone','SLE','694')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1191, 'SG','SINGAPORE','Singapore','SGP','702')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1192, 'SK','SLOVAKIA','Slovakia','SVK','703')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1193, 'SI','SLOVENIA','Slovenia','SVN','705')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1194, 'SB','SOLOMON ISLANDS','Solomon Islands','SLB','090')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1195, 'SO','SOMALIA','Somalia','SOM','706')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1196, 'ZA','SOUTH AFRICA','South Africa','ZAF','710')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1197, 'GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1198, 'ES','SPAIN','Spain','ESP','724')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1199, 'LK','SRI LANKA','Sri Lanka','LKA','144')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1200, 'SD','SUDAN','Sudan','SDN','736')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1201, 'SR','SURINAME','Suriname','SUR','740')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1202, 'SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM','744')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1203, 'SZ','SWAZILAND','Swaziland','SWZ','748')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1204, 'SE','SWEDEN','Sweden','SWE','752')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1205, 'CH','SWITZERLAND','Switzerland','CHE','756')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1206, 'SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1207, 'TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN','158')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1208, 'TJ','TAJIKISTAN','Tajikistan','TJK','762')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1209, 'TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1210, 'TH','THAILAND','Thailand','THA','764')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1211, 'TL','TIMOR-LESTE','Timor-Leste',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1212, 'TG','TOGO','Togo','TGO','768')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1213, 'TK','TOKELAU','Tokelau','TKL','772')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1214, 'TO','TONGA','Tonga','TON','776')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1215, 'TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1216, 'TN','TUNISIA','Tunisia','TUN','788')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1217, 'TR','TURKEY','Turkey','TUR','792')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1218, 'TM','TURKMENISTAN','Turkmenistan','TKM','795')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1219, 'TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1220, 'TV','TUVALU','Tuvalu','TUV','798')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1221, 'UG','UGANDA','Uganda','UGA','800')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1222, 'UA','UKRAINE','Ukraine','UKR','804')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1223, 'AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1224, 'GB','UNITED KINGDOM','United Kingdom','GBR','826')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1225, 'US','UNITED STATES','United States','USA','840')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1226, 'UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL)
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1227, 'UY','URUGUAY','Uruguay','URY','858')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1228, 'UZ','UZBEKISTAN','Uzbekistan','UZB','860')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1229, 'VU','VANUATU','Vanuatu','VUT','548')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1230, 'VE','VENEZUELA','Venezuela','VEN','862')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1231, 'VN','VIET NAM','Viet Nam','VNM','704')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1232, 'VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','092')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1233, 'VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1234, 'WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF','876')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1235, 'EH','WESTERN SAHARA','Western Sahara','ESH','732')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1236, 'YE','YEMEN','Yemen','YEM','887')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1237, 'ZM','ZAMBIA','Zambia','ZMB','894')
INSERT INTO country(id, isoCode, name, printableName, iso3, numcode) VALUES (1238, 'ZW','ZIMBABWE','Zimbabwe','ZWE','716')
